# Generated by Django 5.2.3 on 2025-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_comment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply')], default='comment', max_length=20),
        ),
    ]
