# Generated by Django 5.2.3 on 2025-07-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_notification_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comment_videos/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_images/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='topic_videos/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
