# Generated by Django 5.2.3 on 2025-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_comment_image_comment_video_topic_image_topic_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
