# Generated by Django 5.2.3 on 2025-07-30 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
