# Generated by Django 5.2.3 on 2025-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
