# Generated by Django 5.2.3 on 2025-08-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
    ]
