# Generated by Django 5.2.3 on 2025-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_comment_is_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
