# Generated by Django 5.2.3 on 2025-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_alter_comment_image_alter_comment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
    ]
