# Generated by Django 5.2.3 on 2025-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_fix_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
