# Generated by Django 5.2.3 on 2025-08-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_topic_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Yorum'), ('reply', 'Cevap'), ('like', 'Beğeni'), ('solution', 'Çözüm')], max_length=20),
        ),
    ]
