# Generated by Django 5.2.3 on 2025-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_favorites'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_tags',
            field=models.ManyToManyField(blank=True, related_name='followers', to='taggit.tag'),
        ),
    ]
