# Generated by Django 5.2.3 on 2025-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_followed_tags'),
        ('forum', '0013_topic_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='forum.topic'),
        ),
    ]
